Feature/8392 xlsx   selectrange, copy, paste, getcolor, setcolor
G1ANT-Robot/G1ANT.Addon.Xlsx pull request #8
Opened 2019-08-01 09:35 UTC by folbo

2019-08-21 12:29 UTC, danieladamkaiser requested changes

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx.UnitTests/CellRefTests.cs
> +            CellRef a = new CellRef("sheet", "ABC42");
var

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx.UnitTests/CellRefTests.cs
> +        public void TestConstructor()
Naming convention for tests we are using is Should_When. Would be nice to have it consistent ;)

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx.UnitTests/CellRefTests.cs
> +            CellRef b = new CellRef("sheet", "A", 4);
var

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx.UnitTests/XlsxWrapperTests.cs
> +            //wrapper.GetCellColor(new CellRef("sheet1", "C", 4));
Language was updated to 4.103 so you can uncomment this line now and update one bellow

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/CellRef.cs
> +            long rows = Math.Abs(start.Row - end.Row) + 1;
Int should be enough ;)

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +using System.Xml.Linq;
Remove unused

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +        private static System.Drawing.Color[] _themeColors;
We dont use underscores to mark private fields

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +        public System.Drawing.Color? GetCellBackgroundColor(Cell theCell)
just "cell" param name would be enough i think

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +            Fonts fonts = stylesheet.Fonts;
vars

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +            UInt32 fontIndex = fonts.Count;
just "uint"

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +            CellFormat newformat = (CellFormat)format.Clone();
var

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColumnNamesGenerator.cs
> +                .ToArray();
I really dislike how this collection is recreated everytime we want to getcollumnsbetweeninclusive :/ Maybe we can avoid that somehow?

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/XlsxWrapper.cs
> +                    Cell theCell = wsPart.Worksheet.Descendants<Cell>()
var

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/XlsxWrapper.cs
> +                Cell cell = wsPart.Worksheet.Descendants<Cell>().Where(c => c.CellReference == cellReference.Address).FirstOrDefault();
vars

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/XlsxWrapper.cs
> +                Cell cell = wsPart.Worksheet.Descendants<Cell>().Where(c => c.CellReference == cellReference.Address).FirstOrDefault();
DRY lines: 
437
517
535

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/CellRef.cs
> +            var end = new CellRef(SheetId, endColumn, endRow);
startCell
endCell

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +                theCell.StyleIndex = formatIndex;
Extract code from here and from else. It will look a little bit better

2019-08-21 12:29 UTC, danieladamkaiser commented on G1ANT.Addon.Xlsx/Api/XlsxWrapper.cs
> +                                CellRef cellAdress = new CellRef(sheetID, cell.CellReference);
var

2019-08-30 13:13 UTC, folbo commented on G1ANT.Addon.Xlsx.UnitTests/CellRefTests.cs
> +            CellRef b = new CellRef("sheet", "A", 4);
i won't change it here

2019-08-30 13:26 UTC, folbo commented on G1ANT.Addon.Xlsx.UnitTests/XlsxWrapperTests.cs
> +            //wrapper.GetCellColor(new CellRef("sheet1", "C", 4));
this test won't work anyway, wrapper doesn't have any sheet on init. I'm gonna delete it.

2019-08-30 13:33 UTC, folbo commented on G1ANT.Addon.Xlsx/Api/ColorService.cs
> +        private static System.Drawing.Color[] _themeColors;
ok

2019-08-30 13:42 UTC, folbo commented on G1ANT.Addon.Xlsx/Api/ColumnNamesGenerator.cs
> +                .ToArray();
Moved to static constructor

2019-08-30 13:44 UTC, folbo commented on G1ANT.Addon.Xlsx/Api/XlsxWrapper.cs
> +                Cell cell = wsPart.Worksheet.Descendants<Cell>().Where(c => c.CellReference == cellReference.Address).FirstOrDefault();
won't do

2019-08-30 13:50 UTC, danieladamkaiser approved these changes

2019-08-30 14:13 UTC, merged